spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/bitblog_users
    username: bitblogger
    password: bitmonsters

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/bitblog_users
    user: bitblogger
    password: bitmonsters
    baseline-version: 1
    baseline-on-migrate: true
    baseline-description: "init"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql

server:
  port: 9000
