CREATE TABLE IF NOT EXISTS tags(
    id INT UNIQUE PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(1024) NOT NULL,
    post_count BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tag_history(
    id INT UNIQUE PRIMARY KEY AUTO_INCREMENT NOT NULL,
    tag_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(1024) NOT NULL,
    action VARCHAR(100) NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at DATETIME NOT NULL,

    FOREIGN KEY(tag_id) REFERENCES tags(id)
);

CREATE TABLE IF NOT EXISTS post_tags(
    id BIGINT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    post_id BIGINT NOT NULL,
    tag_id INT NOT NULL,
    added_at DATETIME NOT NULL,

    FOREIGN KEY(tag_id) REFERENCES tags(id)
)