spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: tag-service
          uri: lb:http://TAG-SERVICE
          predicates:
            - Path=/api/v1/tags/**
        - id: topic-service
          uri: lb:http://TOPIC-SERVICE
          predicates:
            - Path=/api/v1/topics/**
        - id: poll-service
          uri: lb:http://POLL-SERVICE
          predicates:
            - Path=/api/v1/polls/**
        - id: like-service
          uri: lb:http://LIKE-SERVICE
          predicates:
            - Path=/api/v1/likes/**
        - id: media-service
          uri: lb:http://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/media/**
        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**
            - Path=/api/v1/posts/{postId}/comments/**

security:
  jwt:
    secret-key: 43b61073dc82e442ef7d7ddfc7cfed2a5e8ba7f5181ae57d962e93f71656bc33
    expiration-time: 5000

server:
  port: 9999