spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitblog_auth
    username: bitblogger
    password: bitmonsters
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/bitblog_auth
    user: bitblogger
    password: bitmonsters
    baseline-version: 1
    baseline-description: "init"
    baseline-on-migrate: true

  mail:
    email: ${MAILTRAP_DEV_EMAIL_ID}
    password: ${MAILTRAP_DEV_EMAIL_PASSWORD}

security:
  jwt:
    secret-key: 43b61073dc82e442ef7d7ddfc7cfed2a5e8ba7f5181ae57d962e93f71656bc33
    expiration-time: 5000

server:
  port: 9998
