spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitblog_auth
    username: bitblogger
    password: bitmonsters
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/bitblog_auth
    user: bitblogger
    password: bitmonsters
    baseline-version: 1
    baseline-description: "init"
    baseline-on-migrate: true

server:
  port: 9998
