spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: bitblogger_content
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: content_group

server:
  port: 9007