spring:
  cassandra:
    schema-action: create_if_not_exists
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    request:
      timeout: 10s
    local-datacenter: dc1
    keyspace-name: likes_space
    contact-points: 127.0.0.1
    port: 9042
    username: cassandra
    password: cassandra

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      TAG-SERVICE:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10

server:
  port: 9001