spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: bitblogger_media

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB


azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container: ${AZURE_STORAGE_CONTAINER_NAME}

server:
  port: 9005