spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitblog_topics
    username: bitblogger
    password: bitmonsters

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql

  flyway:
    user: bitblogger
    password: bitmonsters
    enabled: true
    baseline-version: 1
    baseline-description: "init"
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/bitblog_topics

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      TAG-SERVICE:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10

server:
  port: 9002