spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitblog_topics
    username: bitblogger
    password: bitmonsters

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql

  flyway:
    user: bitblogger
    password: bitmonsters
    enabled: true
    baseline-version: 1
    baseline-description: "init"
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/bitblog_topics

server:
  port: 9002