CREATE TABLE IF NOT EXISTS PLATFORMS (
    id INT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    base_url VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    display_email BOOLEAN DEFAULT FALSE,
    profile_image VARCHAR(1024),
    website_url VARCHAR(100),
    city VARCHAR(50),
    country VARCHAR(50),
    bio TEXT,
    skills TEXT,
    available_for TEXT,
    learnings TEXT,
    pronouns VARCHAR(50),
    work TEXT,
    education TEXT,
    created_at DATETIME NOT NULL,
    modified_at DATETIME
);

CREATE TABLE IF NOT EXISTS USER_LINKS (
    id BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    user_id BIGINT NOT NULL,
    platform INT,
    url VARCHAR(100),
    custom BOOLEAN DEFAULT FALSE,
    created_at DATETIME NOT NULL,
    modified_at DATETIME NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USERS(id),
    FOREIGN KEY (platform) REFERENCES PLATFORMS(id)
);



CREATE TABLE IF NOT EXISTS FOLLOWERS (
    id BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    FOREIGN KEY(follower_id) REFERENCES USERS(id),
    FOREIGN KEY (following_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS USER_REPORTS (
    id BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    user_id BIGINT NOT NULL,
    reporter_id BIGINT NOT NULL,
    reason VARCHAR(256) NOT NULL,
    note TEXT,
    created_at DATETIME NOT NULL,

    FOREIGN KEY(user_id) REFERENCES USERS(id),
    FOREIGN KEY(reporter_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS INTERESTS (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    FOREIGN KEY(user_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS READING_LIST (
    id BIGINT PRIMARY KEY UNIQUE AUTO_INCREMENT NOT NULL,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    note TEXT,

    FOREIGN KEY(user_id) REFERENCES USERS(id)
);

CREATE INDEX idx_email ON USERS(email);
CREATE INDEX idx_username ON USERS(username);